version: '2.1'

services:
  frontend:
    image: dreamsim-frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - API_URL='http://localhost'
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"

