---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-hdd
  namespace: circuit-design-stage
  annotations:
    volume.alpha.kubernetes.io/storage-class: "hdd"
  labels:
    app: app
    stage: stage
    service: circuit-design
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
