apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert
  labels:
    stage: stage
    service: circuit-design
spec:
  secretName: circuit-design-stage-tls
  issuerRef:
    name: letsencrypt-stage
    kind: ClusterIssuer
  dnsNames:
    - circuit-design.ru
    - www.circuit-design.ru
  acme:
    config:
      - ingressClass: nginx
        domains:
          - circuit-design.ru
          - www.circuit-design.ru
