apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert
  labels:
    stage: stage
    service: dreamsim
spec:
  secretName: dreamsim-stage-tls
  issuerRef:
    name: letsencrypt-stage
    kind: ClusterIssuer
  dnsNames:
    - dreamsim.ru
    - www.dreamsim.ru
  acme:
    config:
      - ingressClass: nginx
        domains:
          - dreamsim.ru
          - www.dreamsim.ru
