apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert
  labels:
    stage: stage
    service: dreamsim
spec:
  secretName: dreamsim-stage-tls
  issuerRef:
    name: letsencrypt-stage
    kind: ClusterIssuer
  dnsNames:
    - drsim.ru
    - www.drsim.ru
  acme:
    config:
      - ingressClass: nginx
        domains:
          - drsim.ru
          - www.drsim.ru
