apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
  labels:
    stage: stage
    service: dreamsim
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: n02@yandex.ru
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
