# Generated by Django 2.1.7 on 2019-03-11 22:09

import apps.authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ВУЗа')),
                ('format_group', models.CharField(max_length=30, null=True, verbose_name='Формат названия группы')),
            ],
            options={
                'verbose_name': 'ВУЗ',
                'verbose_name_plural': 'ВУЗы',
            },
        ),
        migrations.CreateModel(
            name='VkLinkValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=30,
                null=True,
                validators=[apps.authentication.validators.GroupValidator],
                verbose_name='Учебная группа'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk',
            field=models.URLField(
                blank=True,
                null=True,
                unique=True,
                validators=[apps.authentication.validators.VkLinkValidator],
                verbose_name='Ссылка ВК'
            ),
        ),
    ]
