# Generated by Django 2.1.7 on 2019-03-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190318_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Учебная группа',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Group'
            ),
        ),
    ]
