# Generated by Django 3.0.5 on 2020-04-08 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_timestamped_element_scheme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat', serialize=False, to='core.Scheme', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('text', models.TextField(max_length=1023, verbose_name='Текст')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtime.Chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MessageReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtime.Message', verbose_name='Сообщение')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Читатель сообщения',
                'verbose_name_plural': 'Читатели сообщений',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='readers',
            field=models.ManyToManyField(through='realtime.MessageReader', to=settings.AUTH_USER_MODEL),
        ),
    ]
