# Generated by Django 2.1.7 on 2019-03-18 19:02

import apps.core.models.element_parameter
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementparameter',
            name='dimension_id',
            field=models.CharField(
                choices=[(apps.core.models.element_parameter.DimensionChoice('м'), 'м'),
                         (apps.core.models.element_parameter.DimensionChoice('мк'), 'мк'),
                         (apps.core.models.element_parameter.DimensionChoice('н'), 'н'),
                         (apps.core.models.element_parameter.DimensionChoice('п'), 'п'),
                         (apps.core.models.element_parameter.DimensionChoice('К'), 'К'),
                         (apps.core.models.element_parameter.DimensionChoice('М'), 'М'),
                         (apps.core.models.element_parameter.DimensionChoice('Г'), 'Г'),
                         (apps.core.models.element_parameter.DimensionChoice('Т'), 'Т')],
                max_length=30,
                verbose_name='Размерность'
            ),
        ),
    ]
